#!/usr/bin/env python3
"""Summarize quality-filtered Goertzel power distributions.

Inputs are CSV files generated by plot_goertzel_vs_raw.py, one per subject/channel.
For each subject and channel, rows with quality > threshold are kept and used to
compute distribution statistics. The script also aggregates all subjects and
writes both summary stats and histogram tables.
"""

from __future__ import annotations

import argparse
import os

import numpy as np
import pandas as pd

from lilia.goertzel_distribution import (
    GroupData,
    collect_group_data,
    common_db_edges,
    with_aggregates,
)


def _safe_quantile(arr: np.ndarray, q: float) -> float:
    if arr.size == 0:
        return float('nan')
    return float(np.quantile(arr, q))


def _group_stats(g: GroupData) -> dict[str, object]:
    keep_ratio = float(g.n_kept / g.n_total) if g.n_total > 0 else float('nan')
    return {
        'subject': g.subject,
        'channel': g.channel,
        'n_total': g.n_total,
        'n_kept_quality_gt_threshold': g.n_kept,
        'keep_ratio': keep_ratio,
        'power_mean': float(np.mean(g.power)) if g.power.size else float('nan'),
        'power_std': float(np.std(g.power, ddof=0)) if g.power.size else float('nan'),
        'power_min': float(np.min(g.power)) if g.power.size else float('nan'),
        'power_p05': _safe_quantile(g.power, 0.05),
        'power_p25': _safe_quantile(g.power, 0.25),
        'power_p50': _safe_quantile(g.power, 0.50),
        'power_p75': _safe_quantile(g.power, 0.75),
        'power_p95': _safe_quantile(g.power, 0.95),
        'power_max': float(np.max(g.power)) if g.power.size else float('nan'),
        'db_mean': float(np.mean(g.power_db)) if g.power_db.size else float('nan'),
        'db_std': float(np.std(g.power_db, ddof=0)) if g.power_db.size else float('nan'),
        'db_min': float(np.min(g.power_db)) if g.power_db.size else float('nan'),
        'db_p05': _safe_quantile(g.power_db, 0.05),
        'db_p25': _safe_quantile(g.power_db, 0.25),
        'db_p50': _safe_quantile(g.power_db, 0.50),
        'db_p75': _safe_quantile(g.power_db, 0.75),
        'db_p95': _safe_quantile(g.power_db, 0.95),
        'db_max': float(np.max(g.power_db)) if g.power_db.size else float('nan'),
    }


def _hist_rows(g: GroupData, edges: np.ndarray) -> list[dict[str, object]]:
    if g.power_db.size == 0:
        rows = []
        for i in range(len(edges) - 1):
            rows.append(
                {
                    'subject': g.subject,
                    'channel': g.channel,
                    'bin_left_db': float(edges[i]),
                    'bin_right_db': float(edges[i + 1]),
                    'count': 0,
                    'fraction': 0.0,
                }
            )
        return rows

    counts, _ = np.histogram(g.power_db, bins=edges)
    total = int(np.sum(counts))
    rows = []
    for i, c in enumerate(counts):
        rows.append(
            {
                'subject': g.subject,
                'channel': g.channel,
                'bin_left_db': float(edges[i]),
                'bin_right_db': float(edges[i + 1]),
                'count': int(c),
                'fraction': float(c / total) if total > 0 else 0.0,
            }
        )
    return rows


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description='Summarize quality-filtered Goertzel power distribution per subject/channel and overall.'
    )
    p.add_argument('--root', default='iBrainCenter', help='Root folder with subject subfolders.')
    p.add_argument('--channels', type=int, nargs='+', default=[1, 2],
                   help='Channels to summarize (default: 1 2).')
    p.add_argument('--target-freq', type=float, default=60.0,
                   help='Goertzel target frequency used in filenames (default 60).')
    p.add_argument('--threshold', type=float, default=0.5,
                   help='Keep rows with quality > threshold (default 0.5).')
    p.add_argument('--exclude-hard-artifact', dest='exclude_hard_artifact',
                   action='store_true', default=True,
                   help='Exclude rows where artifact_hard_clip==1 when available (default on).')
    p.add_argument('--no-exclude-hard-artifact', dest='exclude_hard_artifact',
                   action='store_false',
                   help='Ignore artifact_hard_clip and filter by quality only.')
    p.add_argument('--stem', default='index_vs_raw_goertzel',
                   help='Input CSV filename stem (default index_vs_raw_goertzel).')
    p.add_argument('--bins', type=int, default=30, help='Histogram bin count (default 30).')
    p.add_argument('--outdir', default='iBrainCenter/comparison',
                   help='Output directory for summary files.')
    return p.parse_args()


def main() -> None:
    args = _parse_args()
    os.makedirs(args.outdir, exist_ok=True)

    try:
        base_groups, missing_files = collect_group_data(
            root=args.root,
            channels=args.channels,
            stem=args.stem,
            target_freq=args.target_freq,
            threshold=args.threshold,
            exclude_hard_artifact=args.exclude_hard_artifact,
            require_power=True,
        )
    except ValueError as exc:
        raise SystemExit(str(exc)) from exc

    if missing_files:
        print('Warning: some input CSV files were not found and were skipped:')
        for p in missing_files:
            print(f'  - {p}')

    if not base_groups:
        raise SystemExit('No input data found to summarize.')

    group_rows = with_aggregates(base_groups, args.channels)

    summary_df = pd.DataFrame([_group_stats(g) for g in group_rows])

    edges = common_db_edges(group_rows, args.bins)

    hist_rows = []
    for g in group_rows:
        hist_rows.extend(_hist_rows(g, edges))
    hist_df = pd.DataFrame(hist_rows)

    tag = f"thr_{args.threshold:g}".replace('.', 'p')
    summary_path = os.path.join(args.outdir, f'goertzel_distribution_summary_{tag}.csv')
    hist_path = os.path.join(args.outdir, f'goertzel_distribution_hist_{tag}.csv')

    summary_df.to_csv(summary_path, index=False)
    hist_df.to_csv(hist_path, index=False)

    print(f'Saved: {summary_path}')
    print(f'Saved: {hist_path}')


if __name__ == '__main__':
    main()
